services:
  easeUp-next:
    container_name: TripNest-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/TripNest-next
    working_dir: /usr/src/TripNest-next
    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

    # FOR DEVELOPMENT
    # command: bash -c "npm install && npm run start:dev"

networks:
  client-network:
    driver: bridge
